FCS/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from core import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
    url(r'^posts/$', views.post_list, name='post_list'),
    url(r'^duvidas/$', views.doubtView, name='doubt'),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^post/', include('core.urls', namespace='core')),
    url(r'^admin/', admin.site.urls),
]

core/urls.py
from django.conf.urls import url
from django.contrib import admin

from core import views

urlpatterns = [
	url(r'^(?P<slug>[\w_-]+)$', views.post, name='post'),	
]

core/models.py
from django.db import models

from django.core.urlresolvers import reverse
# Create your models here.

class Author(models.Model):
	name = models.CharField('Nome', max_length=100)

	def __str__ (self):
		return self.name

class Category(models.Model):
	name = models.CharField('Nome', max_length=100)
	slug = models.SlugField('slug', max_length=100)

	def __str__ (self):
		return self.slug


class Post(models.Model):
	title = models.CharField('Titulo', max_length=100)
	slug = models.SlugField('sulg', max_length=100)
	container = models.TextField('Conteudo')
	author = models.ForeignKey('core.Author', verbose_name='Autor')
	category = models.ForeignKey('core.Category', verbose_name='Categoria')

	created = models.DateTimeField('Criado em', auto_now_add=True)
	modified = models.DateTimeField('Modificado em', auto_now=True)

	def __str__ (self):
		return self.slug

core/forms.py
from django import forms

from django.core.mail import send_mail
from django.conf import settings

class DoubtForm (forms.Form):

	name = forms.CharField(label='Nome')
	email = forms.EmailField(label='E-mail')
	message = forms.CharField(label='Mensagem', widget=forms.Textarea())

	def send_mail(self):
		name = self.cleaned_data['name']
		email = self.cleaned_data['email']
		message = self.cleaned_data['message']
		message = 'Nome: {0}\nEmail:{1}\n{2}'.format(name, email,message)
		send_mail('FCS Advogados Associados [Dúvida]', message, settings.DEFAULT_FROM_EMAIL,
			[settings.EMAIL_TO]
		)
		return True

core/views.py
from django.shortcuts import render
from django.views import generic

from .models import Post
from .forms import DoubtForm

# Create your views here.

def index (request):
	posts = Post.objects.all().order_by('-id')

	context = {
		'post1' : posts[0],
		'post2' : posts[1],
		'post3' : posts[2], 
	}
	return render(request, 'index.html', context)


def doubtView (request):
	success = False
	form = DoubtForm(request.POST or None)
	if form.is_valid():
		success = form.send_mail()

	context = {
		'form'	: form,
		'success': success,
	}
	return render (request, 'doubt.html', context)

class PostListView (generic.ListView):
	queryset = Post.objects.all().order_by('-created')
	model = Post
	template_name = 'post_list.html'
	context_object_name = 'posts'
	paginate_by = 10

post_list = PostListView.as_view()

def post (request, slug):
	context = {
		'post' : Post.objects.get(slug=slug),
	}
	return render (request, 'post.html', context)

core/templates/base.html
<!--
Autor: Filipe Cordeiro de Medeiros Azevêdo
url: https://github.com/filipecmedeiros/Ferreira-Costa-Silva-
-->
{% load static %}

<!DOCTYPE HTML>
<html>
	<head>
		<title> {% block title %} Ferreira, Costa & Silva Advogados Associados {% endblock %}</title>
		<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/fav-icon.png' %}" />
		<link href="{% static 'css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
		<link href="{% static 'css/bootstrap.min.css' %}" rel='stylesheet' type='text/css' />
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		 <!-- Custom Theme files -->
		<link href="{% static 'css/theme-style.css' %}" rel='stylesheet' type='text/css' />


   		<script src="{% static 'js/jquery.easing.min.js' %}"></script>
   		 <!-- Custom Theme files -->
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/fav-icon.png' %}" />
		<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
		</script>
		<!--webfonts-->
		<!--<link href='https://fonts.googleapis.com/css?family=Raleway:400,100,300,500,700,800,900,600,200' rel='stylesheet' type='text/css'>-->
		<!--//webfonts-->
		<!--requred-js-files-->
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		    <script src="js/html5shiv.js"></script>
		    <script src="js/respond.min.js"></script>
		<![endif]-->
		<!--//requred-js-files-->
		<script type="text/javascript" 	src="{% static 'js/jquery.smint.js' %}"></script>
		<script type="text/javascript">
			$(document).ready( function() {
			    $('.subMenu').smint({
			    	'scrollSpeed' : 1000
			    });
			});
		</script>
	</head>
	<body onload="setTimeout(function() { window.scrollTo(0, 1) }, 100);">

		<nav class="subMenu navbar-custom navbar-scroll-top" role="navigation">
	        <div class="container">
	            <div class="navbar-header page-scroll">
	                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
	                    <img src="{% static 'images/nav-icon.png' %}" title="drop-down-menu" /> 
	                </button>
	            </div>
	            <!-- Collect the nav links, forms, and other content for toggling -->
	            <div class="collapse navbar-collapse navbar-left navbar-main-collapse">
	                <ul class="nav navbar-nav">
	                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
	                    <li class="active">
	                        <a id="sTop" class="subNavBtn" href="{% url 'index' %}">Home</a>
	                    </li>
	                    <li class="page-scroll">
	                        <a id="s1" class="subNavBtn" href="{% url 'post_list' %}">Notícias</a>
	                    </li>
	                    <li class="page-scroll">
	                        <a id="s2" class="subNavBtn" href="{% url 'index' %}">Quem Somos</a>
	                    </li>
	                    <li class="page-scroll">
	                        <a id="s3" class="subNavBtn" href="{% url 'index' %}">Atuação</a>
	                    </li>
	                    <li class="page-scroll">
	                        <a id="s4" class="subNavBtn" href="{% url 'index' %}">Equipe</a>
	                    </li>
	                    <li class="page-scroll">
	                        <a id="s5" class="subNavBtn" href="{% url 'index' %}">Contato</a>
	                    </li>
	                    <li>
	                        <a class="subNavBtn" href="{% url 'doubt' %}">Dúvidas</a>
	                    </li>
	                </ul>
	            </div>
	            <!-- /.navbar-collapse -->
	             	<a  id="sTop" class="right-msg subNavBtn msg-icon" href="{% url 'index' %}"><span> </span></a>
	                <div class="clearfix"> </div>
	        </div>
	        <!-- /.container -->
   	  </nav>
		<!--start-container-->
		{% block container %}
		{% endblock %}
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
	</body>
</html>


core/templates/doubt.html
{% extends 'base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block container %}
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
	<h1 style="text-align:center; color: #102a50">Mande sua dúvida!</h1>
		<div class="row  section top-grids">
			{% if success %}
				<div class="alert alert-success">
					Mensagem enviada com sucesso!
				</div>
			{% endif %}
			<form class="form-horizontal" action="" method="post">
				<fieldset>
					{% csrf_token %}
					{% for field in form %}
						<div class="form-group {% if field.errors %} has-errors {% endif %}">
					      <label for="{{field.auto_id }}" class="col-md-3 control-label">{{ field.label }}</label>
					      <div class="col-md-9">
					        {% render_field field class='form-control' %}
					      	{% for error in field.errors %}
					      		<span class="help-block">{{error}}</span>
					      	{% endfor %}
					      </div>
					    </div>
					{% endfor %}	
				    
				    
					<div class="form-group">
				      <div class="col-md-9 col-md-offset-3">
				        <button type="submit" class="btn btn-primary btn-red">Enviar</button>
				      </div>
				    </div>
				</fieldset>
			</form>
			</div>
		</div>
{% endblock %}

core/templates/index.html
{% extends 'base.html' %}

{% load static %}


{% block container %}
		<div class="head-bg sTop">
			<div class="container">
				<div class="col-lg-12 header-note">
					<a href="#"><img src="{% static 'images/logo.png' %}" class= "img-responsive"/></a>
					<br/>
					<a class="btn btn-primary big-btn" onclick="rolar()">Apresentação <span></span></a>
				</div>
			</div>
		</div>
		<!--End-container-->
		<!--start-top-nav-->

		<!--//End-top-nav-->

		<!--testmonials-->
		<div  class="testmonials section s1">
 			<div class="container">
 			<div class="bs-example">
 			    <div id="myCarousel" class="carousel slide" data-interval="3000" data-ride="carousel">
 			    	<!-- Carousel indicators -->
 			        <ol class="carousel-indicators pagenate-icons">
 			            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
 			            <li data-target="#myCarousel" data-slide-to="1"></li>
 			            <li data-target="#myCarousel" data-slide-to="2"></li>
 			        </ol>
 
 			       <!-- Carousel items -->
 			        <div class="carousel-inner">
 			            <div class="active item">
 			                <div class="carousel-caption caption">
 			                  <a href="{% url 'core:post' post1.slug %}" style="color:#FFF"><h3>{{ post1.title }}</h3></a>
 			                	<div class="resume">
    								<p>{{ post1.container | safe }}</p>		
								</div>
 			                </div>
 			            </div>
 
 			            <div class="item">
 			                <div class="carousel-caption caption">
 			                  <a href="{% url 'core:post' post2.slug %}" style="color:#FFF"><h3>{{ post2.title }} </h3></a>
 			                  <div class="resume">
 			                  	<p>{{ post2.container | safe }}</p>
 			                  </div>
 			                </div>
 			            </div>
 			            <div class="item">
 			                <div class="carousel-caption caption">
 			                  <a href="{% url 'core:post' post3.slug %}"style="color:#FFF"><h3>{{ post3.title }}</h3></a>
 			                  <div class="resume">
 			                  	<p>{{ post3.container | safe }}</p>
 			                  </div>
 			                </div>
 			            </div>
 			        
  			        </div>
			        <!-- Carousel nav -->
 			    </div>
 			    <a class="btn btn-primary btn-red" href="{% url 'post_list' %}" style="margin-top:50px;">Mais notícias</a>
 			</div>
			</div>
 		</div>

		<!-- start-top-grids-->
		<div style="min-height: 655px;">
		<div class="equipe container s2" >
			<h1 style="text-align:center;padding:1em; color: #102a50">Quem Somos</h1>
			<div class="row  section top-grids">
				<div class="col-lg-2 col-md-2"></div>
				<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 top-grid" style="text-align: justify; font-size:14px;">
					<p>Fundado em maio de 2015, inicialmente sob a razão social Félix, Ferreira, Costa e Silva Advogados Associados, o escritório, no final de 2016, diante de uma alteração societária, passou a ter a denominação de Ferreira, Costa e Silva Advogados Associados.</p>
					<p>O #FCS tem como objetivo primordial garantir os direitos de seus clientes, baseando suas ações sempre na ética e nos princípios legais.</p>
 					<p>Nossa filosofia de trabalho proporciona resultados excelentes, com soluções adequadas àqueles que buscam acesso à justiça.</p>
 					<p>Pautados por uma visão consultiva e extrajudicial dos problemas, o #FCS se destaca na resolução amigável da maioria de seus processos.</p>
 					<p>Entregando assim, resultados mais rápidos, práticos e eficientes aos seus clientes, diminuindo a conhecida morosidade e o alto custo dos processos judiciais. </p>
 					<p>Atuamos nas áreas civil, consumerista, penal, trabalhista e previdenciário, garantindo a nossos clientes um trabalho preciso, dinâmico e personalizado, por meio de uma equipe experiente, e atenta aos novos conceitos jurídicos e em constante atualização.</p>
 					<p>O #FCS cresce a cada ano e espera se consolidar no cenário nacional, tornando-se um dos principais escritórios de advocacia do país.</p>
				</div>
				<div class="col-lg-2 col-md-2"></div>
				<div class="clearfix"> </div>
			</div>
		</div>
		</div>
		<!-- //End-top-grids-->

		<!--start-portfolio-->
		<div class="portfolio section s3">
			<div class="container portfolio-head">
				<h3> Atuação</h3>
				<br/>
				<ul id="filters" class="clearfix">
						<!--<li><span id="a1" class="filter active" onclick="Lista()">Áreas</span></li>-->
						<li><span id="a2" class="filter" onclick="Civil()">Civil</span></li>
						<li><span id="a3" class="filter" onclick="Consumidor()">Consumidor</span></li>
						<li><span id="a3" class="filter" onclick="Penal()">Penal</span></li>
						<li><span id="a4" class="filter" onclick="Trabalhista()">Trabalhista</span></li>
						<li><span id="a5" class="filter" onclick="Previdenciario()">Previdenciário</span></li>
					</ul>
				
					<div style="min-height: 140px; text-align:justify;">
					<div id="lista" >
						<p>
						</p>
					</div>

					<div id="civil">
						<p>
						O FCS ADVOGADOS ASSOCIADOS atua na maior área do direito, conseguindo resultados efetivos, sejam elas referentes as pessoas físicas ou jurídicas. Buscando harmonia na relação entre as partes envolvidas no processo.
						</p>
					</div>
					<div id="consumidor" style="display: none;">
						<p>
							O FCS ADVOGADOS ASSOCIADOS tem como especialidade a defesa do consumidor, sendo assim visa buscar de forma efetiva a melhor conciliação entre cliente e empresa. Procuramos defender o cliente em procedimentos administrativos e judiciais perante órgãos de defesa do consumidor.
						</p>
					</div>
					<div id="penal" style="display: none;">
						<p>
						O FCS ADVOGADOS ASSOCIADOS atua no ramo de direito penal assegurando o respeito aos direitos dos nossos clientes.
						</p>
					</div>
					<div id="trabalhista" style="display: none;">
						<p>
						O FCS ADVOGADOS ASSOCIADOS atua na área trabalhista de forma preventiva, por meio de assessoria jurídica, contenciosa, defendendo os interesses de nossos clientes.
						<br/>
						Oferecemos suporte aos nossos clientes informando-os as corretas práticas trabalhistas, bem como a legislação aplicável ao caso, e havendo necessidade, atuando em processos judiciais e administrativos.
						</p>
					</div>
					<div id="previdenciario" style="display: none;">
						<p>
						O FCS ADVOGADOS ASSOCIADOS atua na área previdenciária, indicando aos clientes sempre o melhor benefício a ser perseguido, como também auxiliando-o em todas as questões ligadas a condutas arbitraria de entidades previdenciárias.
						</p>
					</div>
					</div>
					
					
			</div>
			</div>
			
			<img src="{% static 'images/real-estate-attorney.jpg' %}" class="img-responsive" id="atuacao" />	
				<script type="text/javascript">
				function Mudarestado(el) {
			        var display = document.getElementById(el).style.display;
			        if(display == "none")
			            document.getElementById(el).style.display = 'block';
			        else
			            document.getElementById(el).style.display = 'none';
			    }

			    function rolar(){
			    	console.log("Olá");

			    	selectorHeight = $('.smint').height();
					var goTo =  $('div.'+ "s2").offset().top -selectorHeight;

					// Scroll the page to the desired position!
					$("html, body").animate({ scrollTop: goTo }, 1000);
				}

			    function Lista (){
			    	document.getElementById('trabalhista').style.display = 'none';
			    	document.getElementById('previdenciario').style.display = 'none';
			    	document.getElementById('civil').style.display = 'none';
			    	document.getElementById('consumidor').style.display = 'none';
			    	document.getElementById('penal').style.display = 'none';
			    	document.getElementById('lista').style.display = 'block';
			    }


			    function Civil (){
			    	document.getElementById('trabalhista').style.display = 'none';
			    	document.getElementById('previdenciario').style.display = 'none';
			    	document.getElementById('lista').style.display = 'none';
			    	document.getElementById('consumidor').style.display = 'none';
			    	document.getElementById('penal').style.display = 'none';
			    	document.getElementById('civil').style.display = 'block';			    	
			    }
			    function Consumidor (){
			    	document.getElementById('trabalhista').style.display = 'none';
			    	document.getElementById('previdenciario').style.display = 'none';
			    	document.getElementById('civil').style.display = 'none';
			    	document.getElementById('lista').style.display = 'none';
			    	document.getElementById('penal').style.display = 'none';
			    	document.getElementById('consumidor').style.display = 'block';			    	
			    }
			    function Penal (){
			    	document.getElementById('trabalhista').style.display = 'none';
			    	document.getElementById('previdenciario').style.display = 'none';
			    	document.getElementById('civil').style.display = 'none';
			    	document.getElementById('consumidor').style.display = 'none';
			    	document.getElementById('lista').style.display = 'none';
			    	document.getElementById('penal').style.display = 'block';
			    }

			    function Trabalhista (){
			    	document.getElementById('lista').style.display = 'none';
			    	document.getElementById('previdenciario').style.display = 'none';
			    	document.getElementById('civil').style.display = 'none';
			    	document.getElementById('consumidor').style.display = 'none';
			    	document.getElementById('penal').style.display = 'none';
			    	document.getElementById('trabalhista').style.display = 'block';
			    }

			    function Previdenciario (){
			    	document.getElementById('trabalhista').style.display = 'none';
			    	document.getElementById('lista').style.display = 'none';
			    	document.getElementById('civil').style.display = 'none';
			    	document.getElementById('consumidor').style.display = 'none';
			    	document.getElementById('penal').style.display = 'none';
			    	document.getElementById('previdenciario').style.display = 'block';
			    }
				</script>			
		<!--//End-portfolio-->
		<!-- start-top-grids-->
		<div style="min-height: 655px;">
		<div class="equipe container s4" >
			<h1 style="text-align:center;padding:1em; color: #102A50">Equipe</h1>
			<div class="row  section top-grids">
				<div class="col-md-4 top-grid">
					<span class="icon1"> </span>
					<h2>Augusto Cesar Silva Ferreira</h2>
					<p>
					Advogado com atuação em Direito do Trabalho e Previdenciário.
 					<br/>
					Graduado em direito pela Faculdade Boa Viagem.
					Pós graduando em Direito e Processo do Trabalho e Direito Previdenciário pela Faculdade Estácio.
					<br/>
					Idiomas: inglês.
					<br/>
					E-mail: aferreira@fcs.adv.br
					</p>
				</div>
				<div class="col-md-4 top-grid">
					<span class="icon2"> </span>
					<h2>Maurílio Sergio Silva Filho</h2>
					<p>
					Advogado com atuação em Direito do Trabalho.
					<br/>
					Graduado em direito pela Faculdade de Ciências Humanas da Sociedade Pernambucana de Cultura e Ensino – SOPECE.
					Pós graduado em Direito Judiciário e Magistratura do Trabalho pela Escola de Magistratura do Trabalho – ESMATRA VI.
					<br/>
					Idiomas: inglês.
					<br/>
					E-mail: msilva@fcs.adv.br
					</p>
				</div>
				<div class="col-md-4 top-grid">
					<span class="icon3"> </span>
					<h2>Rodrigo Jose Silva Costa</h2>
					<p>
					Advogado com atuação em Direito Cível e Consumidor, com ênfase em Juizados Especiais.
					<br/>
					Graduado em direito pela Faculdade Boa Viagem.
					Pós graduando em Direito Civil e Processual Civil pela Faculdade Estácio.
					<br/>
					Idiomas: inglês.
					<br/>
					E-mail: rcosta@fcs.adv.br
					</p>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
		</div>
		<!-- //End-top-grids-->
		
		<!--start-contact-->
		<div class="contact section s5" style="min-height: 655px;">
			<div class="container">
				<h4>Contato</h4>
				<p class="contact-head"><br/></p>
				<div class="row" style="font-size: 10pt; color: #102A50;">
					<div class="col-md-6" style="font-family:arial; margin-top: 5%;">
						<p>Endereço: <br/>
						Rua Coronel Waldemar Basgal, nº 158<br/>
						Piedade, Jaboatão dos Guararapes/PE, CEP:54400-170 <br/>
						Priori Corporate Center, 2º andar, Sala 211 <br/>
						<br/><br/>
						Telefone: (81) 3343-4032 <br/>
						E-mail: aferreira@fcs.adv.br
						</p>
					</div>
					<div class="col-md-6 textarea">
						<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3949.676174751316!2d-34.90748235015547!3d-8.134411894115729!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x7ab1fccc1bb99bf%3A0x3d38ba15d9611f41!2sFerreira%2C+Costa+%26+Silva+Advogados+Associados+-+FCS!5e0!3m2!1spt-BR!2sbr!4v1487684361156" width="100%" height="370" frameborder="0" style="border:0" allowfullscreen></iframe>
					</div>
					<div class="clearfix"> </div><br />
				
				</div>
				<!--start-social-icons-->
				<div class="social-icons">
					<ul>
						<li><a class="facebook" href="https://www.facebook.com/ferreiracostaesilva"> <span> </span></a></li>
						<!--<li><a class="twitter" href="#"> <span> </span></a></li>-->
					</ul>
				</div>
				<!--//End-social-icons->
			</div>
		</div>
		<!-//End-contact-->
		<!-- Include all compiled plugins (below), or include individual files as needed -->
		
{% endblock %}

core/templates/post.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }} | {{ block.super }}
{% endblock %}

{% block container %}
    <div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <!-- Title -->
                <h1>{{ post.title }}</h1>

                <!-- Author -->
                <p class="lead">por {{ post.author.name }}</a></p>
                <hr>
                <!-- Date/Time -->
                <p>{{ post.created }}</p>
                <hr>
                <hr>
                <!-- Post Content -->
                <p>{{ post.container | safe}}</p>
                <hr>
            </div>
                        
        </div>
        <!-- /.row -->

        <hr>
    </div>
{% endblock %}

core/templates/post_list.html
{% extends 'base.html' %}

{% load static %}

{% block container %}

    {% for post in posts %}
        <div class="container">

            <div class="row">

                <!-- Blog Post Content Column -->
                <div class="col-lg-8">

                    <!-- Title -->
                    <a href="{% url 'core:post' post.slug %}"><h1>{{ post.title }}</h1></a>

                    <!-- Author -->
                    <p class="lead">por {{ post.author.name }}</p>
                    <hr>
                    <!-- Date/Time -->
                    <p>{{ post.created }}</p>
                    <hr>
                    <hr>
                    <!-- Post Content -->
                    <p>{{ post.container | safe }}</p>
                    <hr>
                </div>
                            
            </div>
    {% endfor %}
    <!-- /.row -->
    {% if is_paginated %}
      <ul class="pager">
        {% if page_obj.has_previous %}
          <li>
            <a href="/posts?page={{page_obj.previous_page_number}}">«</a>
          </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
          {% if page_obj.number == i %}    
            <li class="active"><a href="?page={{i}}">{{i}}</a></li>
          {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li>
            <a href="/posts?page={{page_obj.next_page_number}}">»</a>
          </li>
        {% endif %}
      </ul>
    {% endif %}
{% endblock %}